### ISSUE TITLE
Box Filter Question

### ISSUE THREAD

**Issue by NikolaAndro** [amazingyyc/SiftySifty#2]
@amazingyyc  Thank you for sharing your implementation.

I am trying to understand your approach for box_filter.cpp file and I am having hard time. More precisely with lines 47-60.

Would you mind explaining what you did in those lines? 

Thank you,

Nikola

**Comment by amazingyyc** [comment]
> @amazingyyc Thank you for sharing your implementation.
> 
> I am trying to understand your approach for box_filter.cpp file and I am having hard time. More precisely with lines 47-60.
> 
> Would you mind explaining what you did in those lines?
> 
> Thank you,
> 
> Nikola

BoxFilter is MeanFilter
suppose a image pixel in one row value is:
`
src[N] = [s0, s1,..., sn-1]
`
Then the BoxFilter with filter radius, `dst[N]` will be:
`
dst[i] = sum(src[i-radius, ..., i, ..., i+radius]) / (2 * radius+1)
`
So `dst[i + 1]` will be:
`
dst[i + 1] = sum(src[i-radius + 1, ..., i , ..., i+radius+1]) / (2 * radius+1)
`
Suppose the 
`S=sum(s[i-radius, ..., i, ..., i+radius])`
Then
`dst[i]=S/(2 * radius+1)`
and
`dst[i+1]=(S-src[i-radius]+src[i+radius+1])/(2 * radius+1)`

line47-49 is sum the first `2*radius+1` pixel value
line54-56 is remove the first pixel value and add the last pixel value for `dstData[x]`

About:`(T) ((sum * scale + delta) >> shift);`
Suppose you have a code like:
```
// y/x both int value
y = x / 10.0
```
So above code is `float` operator is must cost (float divide is cost).
We can convert above code to:
```
y = x / 10.0 = x * 0.1=x * 0.1 * 1024 / 1024 = x * 102.4 / 1024
```
OK `x * 102.4 / 1024` is still float operator so let's use `int` instead of it:
```
// delta represent the half adjust
y = x * 102.4 / 1024 approximately equal to y = (x * 102 + delta) / 1024 = (x*102 + delta) >> 10 
```
Let's verify it.
```
// x = 100
y = x / 10.0=100 / 10.0=10
y=(x*102 + 512) >> 10 =10

// x=202
y=x/10.0=202/10.0=20.2=20
y=(x*102 + 512) >> 10 =20
```
So use `integer` multiply and bit-operate can instead of `float` operate. 
The BoxFilter is used for **image** so it's ok to lost the precision.

**Comment by NikolaAndro** [comment]
Thank you very much! This was a very thorough explanation. I had to to some computations by hand to prove this to myself and it actually works! 

It is a very interesting method for computing the mean for the row. I am assuming this approach was used for the cost purposes. 

Once you compute the mean for every pixel in the row, I am assuming that you are moving the pointer srcData to the next ''row.'' In this case since the data is sequential, just adding the width to move the pointer further down the row in memory. Why adding radius2 to it as well in line 59 and adding only width for the dstData?

**Comment by amazingyyc** [comment]
Look at line:137, the srcData initialized with 
```
(T *) malloc(sizeof(T) * (width + radius2) * height);
```
🤣 
BTW, the project is written for practice🤣 , it may has some unreasonable code code snippet

**Comment by NikolaAndro** [comment]
Thank you anyway!
